apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: helm-api
  name: helm-api
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/helm-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helm-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm-api
    spec:
      containers:
      - env:
        - name: LOGROTATE
          valueFrom:
            configMapKeyRef:
              key: LOGROTATE
              name: helm-api
        - name: LOGROTATE_CONF
          valueFrom:
            configMapKeyRef:
              key: LOGROTATE_CONF
              name: helm-api
        image: mycluster.icp:8500/ibmcom/icp-audit-service:3.1.0
        imagePullPolicy: IfNotPresent
        name: audit-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/systemd/journal
          name: journal
        - mountPath: /var/log/audit
          name: shared
        - mountPath: /etc/logrotate.d/audit
          name: logrotate
          subPath: audit
        - mountPath: /etc/logrotate.conf
          name: logrotate-conf
          subPath: logrotate.conf
      - env:
        - name: RUDDER_TILLER_ADDRESS
          value: tiller-deploy.kube-system:44134
        - name: RUDDER_CLIENT_CERTS
          value: /etc/certs
        - name: USE_TLS
          value: "true"
        image: mycluster.icp:8500/ibmcom/icp-helm-rudder:3.1.0
        imagePullPolicy: IfNotPresent
        name: rudder
        ports:
        - containerPort: 5000
          name: p5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: rudder-certs
      - env:
        - name: DBHOST
          value: mongodb
        - name: DBPORT
          value: "27017"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              key: user
              name: icp-mongodb-admin
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              key: password
              name: icp-mongodb-admin
        - name: MONGO_ISSSL
          value: "true"
        - name: MONGO_SSL_CA
          value: /certs/mongodb-ca/tls.crt
        - name: MONGO_SSL_CERT
          value: /certs/mongodb-client/tls.crt
        - name: MONGO_SSL_KEY
          value: /certs/mongodb-client/tls.key
        - name: ISICP
          value: "true"
        - name: CLUSTER_URL
          value: https://icp-management-ingress:8443
        - name: PLATFORM_IDENTITY_PROVIDER_URL
          value: http://platform-identity-provider:4300
        - name: CLUSTER_PORT
          value: "8443"
        - name: WLP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_ID
              name: platform-oidc-credentials
        - name: WLP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_SECRET
              name: platform-oidc-credentials
        - name: cfcRouterUrl
          value: https://icp-management-ingress:8443
        - name: WLP_REDIRECT_URL
          value: http://localhost:3000/auth/liberty/callback
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
          value: 159.8.223.117,mycluster.icp,mongodb,platform-identity-provider,platform-identity-management,icp-management-ingress,localhost,127.0.0.1
        - name: PROXY_EXTERNAL_ADDR
          value: 159.8.223.117
        - name: CLUSTER_CA_DOMAIN
          value: mycluster.icp
        - name: SET_TLS
          value: "true"
        - name: SERVICE_NAME
          value: helmapi
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AUDIT_ENABLED
          valueFrom:
            configMapKeyRef:
              key: AUDIT_ENABLED
              name: helm-api
        - name: AUDIT_LOG_PATH
          valueFrom:
            configMapKeyRef:
              key: AUDIT_LOG_PATH
              name: helm-api
        image: mycluster.icp:8500/ibmcom/icp-helm-api:3.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: helmapi
        ports:
        - containerPort: 3000
          name: helm-api
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs/mongodb-ca
          name: mongodb-ca-cert
        - mountPath: /certs/mongodb-client
          name: mongodb-client-cert
        - mountPath: /etc/certs
          name: helmapi-certs
        - mountPath: /var/log/audit
          name: shared
      dnsPolicy: ClusterFirst
      nodeSelector:
        master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: mongodb-client-cert
        secret:
          defaultMode: 420
          secretName: cluster-ca-cert
      - name: mongodb-ca-cert
        secret:
          defaultMode: 420
          secretName: cluster-ca-cert
      - name: helmapi-certs
        secret:
          defaultMode: 420
          secretName: helmapi-secret
      - name: rudder-certs
        secret:
          defaultMode: 420
          secretName: rudder-secret
      - hostPath:
          path: /run/systemd/journal
          type: ""
        name: journal
      - emptyDir: {}
        name: shared
      - configMap:
          defaultMode: 420
          items:
          - key: LOGROTATE
            path: audit
          name: helm-api
        name: logrotate
      - configMap:
          defaultMode: 420
          items:
          - key: LOGROTATE_CONF
            path: logrotate.conf
          name: helm-api
        name: logrotate-conf
status: {}