#  Build docker image of db2 express-C v10.5 FP5 (64bit)
FROM ibmcom/db2express-c
ENTRYPOINT ["/bin/bash", "-c", "wget https://raw.githubusercontent.com/SaifRehman/ICP-Airways/master/dataset/flights.csv "]
